name: ci

on:
  pull_request:
  push:
    branches: [main]
    tags:
      - "*"

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: 1.22

      - name: build
        run: go build shareasecret.go

      - name: test
        run: go test ./... -v
