name: release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release-binary-archives:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        os: [linux, darwin, windows]
        arch: [amd64, arm, arm64]
        exclude:
          - os: darwin
            arch: arm
          - os: windows
            arch: arm
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22

      - name: Build Release
        run: ./build/ci/build_release.sh ${{ matrix.os }} ${{ matrix.arch }} ${{ github.ref_name }}

      - name: Create and Publish Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./build/tmp/*
          prerelease: ${{ contains(github.ref_name, '-alpha') || contains(github.ref_name, '-beta') }}

  release-docker-container:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/lsymds/shareasecret
          flavor: latest=false
          tags: |
            type=semver,pattern={{version}}
            type=raw,value=latest,enable=${{ !contains(github.ref_name, '-alpha') && !contains(github.ref_name, '-beta') }}

      - name: Build amd64
        run: ./build/ci/build_release.sh linux amd64 ${{ github.ref_name }} false

      - name: Build arm
        run: ./build/ci/build_release.sh linux arm ${{ github.ref_name }} false

      - name: Build arm64
        run: ./build/ci/build_release.sh linux arm64 ${{ github.ref_name }} false

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./build/package/Dockerfile
          platforms: linux/amd64, linux/arm, linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
